### ISSUE TITLE
Add example with customized level and format of logs 

### ISSUE THREAD

**Issue by biosmooth** [wonder-mice/zf_log#12]
This [commit](https://github.com/biosmooth/zf_log/commit/f101528a0aef341586df0143578938943b08071c) might be useful.

**Comment by wonder-mice** [comment]
I think this example is a bit too complex and has a lot of code that is not related to logging library (like argv parsing). Maybe if you tell what specific point you wanted to show in this example, we can come up with a simpler version.

**Comment by biosmooth** [comment]
Indeed, quite complex :).
@wonder-mice I wanted to show how easily log level and log format can be changed during the program execution.
