### ISSUE TITLE
Wireshark like memory dump.

### ISSUE THREAD

**Issue by paulsubrata55** [wonder-mice/zf_log#26]
TO enable wireshark like memory dump:
02-24|13:44:38.552|27371|27371|V|TestStub.x|main@logger.c:137| 53 6f 6d 65 74 68 69 6e  67 20 69 6d 70 6f 72 74   Something import
02-24|13:44:38.552|27371|27371|V|TestStub.x|main@logger.c:137| 61 6e 74 20 69 73 20 68  65 72 65 20 69 6e 20 6d   ant is here in m
02-24|13:44:38.552|27371|27371|V|TestStub.x|main@logger.c:137| 65 6d 6f 72 79 20 3a 20  61 6b 6a 73 64 6b 6a 61   emory : akjsdkja
02-24|13:44:38.552|27371|27371|V|TestStub.x|main@logger.c:137| 68 73 64 6a 61 6a 68 64  68 6a 61 67 73 64 68 67   hsdjajhdhjagsdhg
02-24|13:44:38.552|27371|27371|V|TestStub.x|main@logger.c:137| 61 73 68 64 67 68 6a 61  73 64 67 61 67 73 64 6a   ashdghjasdgagsdj
02-24|13:44:38.552|27371|27371|V|TestStub.x|main@logger.c:137| 68 61 67 73 64 68 6a 61  67 73 6a 64 61 73 64 6a   hagsdhjagsjdasdj
02-24|13:44:38.552|27371|27371|V|TestStub.x|main@logger.c:137| 61 67 73 64 6a 67 00                               agsdjg?

**Comment by wonder-mice** [comment]
There is no description or justification why anybody on earth will want/need it. Neither it describes what "wireshark like" is. Closing.
