### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by Leandros** [wonder-mice/zf_log#30]
Your `snprintf` implementation does not properly zero-terminate buffers, you might want to take a look here: https://github.com/mpaland/printf/issues/7

Just a nice hint for you, since I saw you using the library and just discovered these issues.

**Comment by wonder-mice** [comment]
Thanks. `zf_log` doesn't rely on this string to be null terminated though. It uses returned length.

**Comment by Leandros** [comment]
Might or might not be correct, either.
