### ISSUE TITLE
CMake instructions use wrong var name

### ISSUE THREAD

**Issue by aaronfrary** [wonder-mice/zf_log#32]
Under the "Embedding with CMake" header in the README is the line
```
set(ZF_LOG_ANDROID_LOG ON)
```
The correct variable name is `ZF_LOG_USE_ANDROID_LOG`.

Happy to submit a PR if that'd be helpful. I'm using this library for a cross-platform project and it's been great so far.

**Comment by wonder-mice** [comment]
Fixed in 0e81882.
