### ISSUE TITLE
Checkmarx static analysis reports a CPPBufferOverflow / ImproperNullTermination on zf_log.c on line 953

### ISSUE THREAD

**Issue by bdurant** [wonder-mice/zf_log#48]
Checkmarx static analysis reports a CPPBufferOverflow / ImproperNullTermination on zf_log.c on line 953:

![Screen Shot 2022-11-14 at 7 19 41 PM](https://user-images.githubusercontent.com/9664396/201818733-e1b02afc-e318-4dbd-a4a7-12f2b12259de.png)

**Comment by wonder-mice** [comment]
False positive, null termination is done later and range is checked above. Also there are a lot of unit tests that test overflow scenario.

**Comment by bdurant** [comment]
Thank you for taking a look and verifying that it is a false positive.
